// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1gm0cTgMe0LAAtHteIhfklQ9nUCe3Yg',
    appId: '1:797813914044:web:69757592b0e5be1f1113b9',
    messagingSenderId: '797813914044',
    projectId: 'app-gastos-9506c',
    authDomain: 'app-gastos-9506c.firebaseapp.com',
    storageBucket: 'app-gastos-9506c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkow6Y0zpV3JjlMev7weqd-od9-uDWIsc',
    appId: '1:797813914044:android:24c0cb58ede494ad1113b9',
    messagingSenderId: '797813914044',
    projectId: 'app-gastos-9506c',
    storageBucket: 'app-gastos-9506c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZirHzpO4APSlB79-xLjU7saEeggjI2GY',
    appId: '1:797813914044:ios:b4560f59448215fe1113b9',
    messagingSenderId: '797813914044',
    projectId: 'app-gastos-9506c',
    storageBucket: 'app-gastos-9506c.firebasestorage.app',
    iosBundleId: 'com.example.gastosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZirHzpO4APSlB79-xLjU7saEeggjI2GY',
    appId: '1:797813914044:ios:b4560f59448215fe1113b9',
    messagingSenderId: '797813914044',
    projectId: 'app-gastos-9506c',
    storageBucket: 'app-gastos-9506c.firebasestorage.app',
    iosBundleId: 'com.example.gastosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr1gm0cTgMe0LAAtHteIhfklQ9nUCe3Yg',
    appId: '1:797813914044:web:76222cc6131745471113b9',
    messagingSenderId: '797813914044',
    projectId: 'app-gastos-9506c',
    authDomain: 'app-gastos-9506c.firebaseapp.com',
    storageBucket: 'app-gastos-9506c.firebasestorage.app',
  );
}
